language: java

jdk:
  - oraclejdk8

before_install:
  - mysql -e 'CREATE DATABASE shop;'

test:
  adapter: mysql
  database: shop
  username: root
  encoding: utf8

#install:
#  - pip install coveralls

notifications:
  email:
    recipients:
      - zhouwentao16@gmail.com

#after_success:
#  - coveralls